ERROR_CODES = 
  RPL_WELCOME: 1
  RPL_YOURHOST: 2
  RPL_CREATED: 3
  RPL_MYINFO: 4

  RPL_NAMREPLY: 353
  RPL_ENDOFNAMES: 366

  NICK_MISSING_NICK: 341
  
  ERR_NOSUCHNICK: 401
  ERR_UNKNOWNCOMMAND: 421
  ERR_SUMMONDISABLED: 445
  ERR_USERSDISABLED: 446
  ERR_NOTREGISTERED: 451
  ERR_NEEDMOREPARAMS: 461
  ERR_ALREADYREGISTRED: 462
  ERR_NOPERMFORHOST: 463
  ERR_PASSWDMISMATCH: 464

  ERR_NOTONCHANNEL: 441
  ERR_NOSUCHCHANNEL: 403

module.exports = 
  ERROR_CODES: ERROR_CODES
  normalize: (name) -> name && name.toLowerCase()
